version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 100
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: "weekly"
