name: Test
on:
  push:
    branches:
      - main
      - $default-branch
  pull_request:
    branches:
      - main
      - $default-branch
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16.x
          - 18.x
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn run build
      - run: yarn run test
      - run: yarn run lint
